export * from "./constants.js";
export {
  type ActorKind,
  type CallerAliasMap,
  type CallerRole,
  type ResolveCallerInput,
  type ResolvedCaller,
  SYSTEM_ACTOR_IDS,
  actorKind,
  isReservedId,
  normaliseCallerId,
  resolveCaller,
  toCanonicalId,
} from "./caller-identity.js";
export { type CallerIdAudit, type CallerIdGroup, auditCallerIds } from "./caller-audit.js";
export {
  type TombstoneRef,
  contentFingerprint,
  curationContentFingerprint,
  curationNormalizedTitle,
  matchesTombstone,
  normalizeForFingerprint,
  normalizedTitle,
} from "./grooming-fingerprint.js";
export { type RedactionResult, redactSecrets } from "./grooming-redaction.js";
export {
  type PrepassFinding,
  type PrepassFindingKind,
  type PrepassResult,
  deterministicPrepass,
} from "./grooming-prepass.js";
export {
  type CuratorPromptInput,
  CURATOR_PROMPT_VERSION,
  buildCuratorPrompt,
} from "./curator-prompt.js";
export {
  type GroomingMemoryInput,
  type GroomingMemoryPatch,
  type GroomingOperation,
  type ParsedGroomingOutput,
  type RejectedOperation,
  GroomingOperationSchema,
  parseGroomingOutput,
} from "./grooming-output.js";
export {
  type OperationOutcome,
  type ValidatedOperation,
  type ValidationContext,
  validateOperations,
} from "./grooming-validate.js";
export {
  type ApplyDecision,
  type ApplyDecisionInput,
  type CuratorOperationType,
  APPLY_CONFIDENCE_THRESHOLD_KEY,
  DEFAULT_APPLY_CONFIDENCE_THRESHOLD,
  decideApplication,
  readApplyConfidenceThreshold,
  writeApplyConfidenceThreshold,
} from "./curator-apply-policy.js";
export {
  type ApplyDeps,
  type ApplyStore,
  type ApplySummary,
  applyOperations,
} from "./grooming-apply.js";
export { type RunCurationCaps, type RunCurationOptions, runCuration } from "./grooming-worker.js";
export {
  type ScheduleSpec,
  isIntakeSweepDue,
  isScheduleDue,
  nextScheduleFire,
} from "./grooming-schedule.js";
export { findLegacyScheduleKeys } from "./grooming-config.js";
export {
  type GroomingTrigger,
  type RunDueCurationOptions,
  type RunDueCurationSummary,
  runDueCuration,
} from "./grooming-enqueue.js";
export {
  type GroomingTickOptions,
  type GroomingTickResult,
  type GroomingTickSkipReason,
  type ScheduledGroomingOptions,
  type ScheduledGroomingResult,
  type ScheduledGroomingSkipReason,
  runGroomingTick,
  runScheduledGrooming,
} from "./grooming-tick.js";
export {
  type IntakeTickOptions,
  type IntakeTickResult,
  type IntakeTickSkipReason,
  runIntakeTick,
} from "./intake-tick.js";
export {
  type GroomingTriggerDecision,
  type GroomingTriggerInputs,
  type MaybeTriggerGroomingOptions,
  type MaybeTriggerGroomingResult,
  evaluateGroomingTrigger,
  maybeTriggerGroomingAfterIntake,
} from "./grooming-trigger.js";
export {
  type SerialScheduler,
  type SerialSchedulerOptions,
  createSerialScheduler,
} from "./serial-scheduler.js";
export {
  type GroomingMemoryRecord,
  type GroomingMemorySource,
  type GroomingTombstoneRecord,
  type EvidenceSlice,
  type MemoryEvidenceBundle,
  type MemoryEvidenceCaps,
  type MemoryEvidenceItem,
  type SliceKind,
  type TombstoneItem,
  gatherMemoryEvidence,
} from "./grooming-evidence.js";
export {
  type GroomingVaultMemoryReader,
  createVaultGroomingMemorySource,
} from "./grooming-source-vault.js";
export {
  type ApplyIntakeDeps,
  type IntakeInboxItemDeps,
  type IntakeResult,
  type IntakeCandidates,
  type IntakeJudgment,
  type IntakeLogger,
  type IntakeOutcome,
  type IntakeApplyStore,
  type IntakeStoredMemory,
  type IntakeSweepDeps,
  type IntakeTocEntry,
  type JudgeSubmissionDeps,
  type JudgeSubmissionInput,
  type JudgeSubmissionResult,
  type LogErrorSink,
  type NavigateDeps,
  type NavigateOptions,
  type ParsedIntakeJudgment,
  type SweepSummary,
  INTAKE_OPERATION_OF,
  IntakeJudgmentSchema,
  applyIntakeJudgment,
  augmentBody,
  intakeInboxItem,
  judgeSubmission,
  navigateInbox,
  parseIntakeJudgment,
  preservesOriginal,
  runIntakeSweep,
} from "./intake/index.js";
export {
  type LlmClient,
  type LlmClientConfig,
  type LlmClientDeps,
  type LlmCompletion,
  type LlmCompletionRequest,
  type LlmErrorKind,
  type LlmMessage,
  type LlmRole,
  type LlmUsage,
  LlmClientError,
  createGroomingLlmClient,
} from "./grooming-llm-client.js";
export {
  type FileIo,
  type LoadedSecretKey,
  decryptSecret,
  encryptSecret,
  loadOrCreateSecretKeyFile,
  resolveOptionalSecretKey,
  resolveSecretKey,
} from "./secret-crypto.js";
export {
  type GroomingConfig,
  type GroomingConfigPatch,
  GroomingConfigPatchSchema,
  GROOMING_ENABLED_KEY,
  LAST_SCHEDULED_GROOM_KEY,
  LEGACY_GROOMING_ENABLED_KEY,
  migrateJobEnablement,
  migrateGroomingSchedule,
  readGroomingConfig,
  readLastScheduledGroomAt,
  writeGroomingConfig,
  writeLastScheduledGroomAt,
} from "./grooming-config.js";
export {
  INTAKE_ENABLED_KEY,
  INTAKE_INTERVAL_MINUTES_KEY,
  type IntakeConfig,
  type IntakeConfigPatch,
  IntakeConfigPatchSchema,
  isIntakeEnabled,
  LAST_INTAKE_SWEEP_KEY,
  readIntakeInterval,
  readLastIntakeSweepAt,
  setIntakeEnabled,
  writeIntakeInterval,
  writeLastIntakeSweepAt,
} from "./intake-config.js";
export {
  ADDENDUM_MAX_BYTES,
  type AddendumStore,
  type CuratorJob,
  type JobAddendum,
  LEGACY_PROMPT_ADDENDUM_KEY,
  migrateCuratorAddendum,
  readJobAddendum,
  setJobAddendum,
} from "./curator-addendum.js";
export {
  type ChatGroundingMemory,
  type ChatGroomingOp,
  type ChatIntakeOp,
  type ChatJob,
  type ChatJobHistory,
  type ChatMemoryGrounding,
  type ChatResponse,
  type ProposedAction,
  ProposedActionSchema,
  buildGroundedMessages,
  inferChatJob,
  parseChatOutput,
  runChatTurn,
} from "./grooming-chat.js";
export {
  type LlmConnection,
  type LlmConnectionKeys,
  type LlmConnectionPatch,
  type LlmConnectionReader,
  type LlmConnectionWriter,
  LlmConnectionPatchSchema,
  llmConnectionKeys,
  readLlmConnection,
  resolveLlmToken,
  writeLlmConnection,
} from "./llm-connection.js";
export {
  type LlmProvider,
  type LlmProviderInput,
  type LlmProviderPatch,
  LlmProviderInputSchema,
  LlmProviderPatchSchema,
  addProvider,
  deleteProvider,
  getProvider,
  listProviderIds,
  listProviders,
  resolveProviderToken,
  updateProvider,
} from "./llm-providers.js";
export {
  type ConsumerConfig,
  type ConsumerConfigPatch,
  type CuratorConsumer,
  type LlmConsumer,
  CURATOR_CONSUMERS,
  ConsumerConfigPatchSchema,
  migrateLegacyCuratorLlm,
  readConsumerConfig,
  resolveConsumerToken,
  writeConsumerConfig,
} from "./curator-consumers.js";
export {
  type BackfillChange,
  type BackfillOptions,
  type BackfillSection,
  type CallerBackfillReport,
  backfillCallerIds,
} from "./caller-backfill.js";
export { formatRecall } from "./formatters/index.js";
export {
  type CorpusDocument,
  type CorpusFrontmatter,
  type InboxDeps,
  type InboxItem,
  type InboxItemRef,
  type InboxSubmissionHints,
  type Vault,
  type VaultOptions,
  type Wikilink,
  CorpusFrontmatterSchema,
  claimInboxItem,
  completeInboxItem,
  createVault,
  listInbox,
  parseDocument,
  parseInboxItem,
  parseWikilinks,
  releaseStaleClaims,
  relinkVault,
  renameWikilinkTarget,
  resolveVaultPath,
  serializeDocument,
  serializeInboxItem,
  writeInbox,
} from "./store/corpus/index.js";
export {
  type VaultLinkIndex,
  type VaultLinkIndexOptions,
  buildVaultLinkIndex,
} from "./store/corpus/vault-links.js";
export {
  type VaultFileKind,
  type VaultFileRead,
  type VaultFileStore,
  type VaultFileStoreDeps,
  type VaultTreeNode,
  VaultFileExistsError,
  VaultFileNotFoundError,
  VaultPathError,
  VaultValidationError,
  VaultWriteConflictError,
  assertVaultFilePath,
  createVaultFileStore,
  validateVaultFile,
  vaultFileKind,
} from "./store/vault-files.js";
export {
  type FileCommit,
  type GitHistory,
  type GitHistoryFileDiffOptions,
  type GitOps,
  type GitPushAuth,
  type SyncGitOps,
  type VaultCommit,
  GitHashError,
  assertCommitHash,
  cloneVaultBackup,
  createGitHistory,
  createGitOps,
  createSyncGitOps,
} from "./store/git/index.js";
export {
  type CachedChunkVector,
  type ChunkOptions,
  type Embedder,
  type EmbeddingCache,
  type EmbeddingCacheOptions,
  type HybridHit,
  type HybridIndex,
  type KeywordHit,
  type KeywordIndex,
  type LinkGraph,
  type LinkGraphOptions,
  type LlamaEmbedderOptions,
  type RecallDeps,
  type RecallOptions,
  type RecalledDoc,
  type ReferenceChunk,
  type ResolveEmbedderOptions,
  type VectorHit,
  type VectorIndex,
  DEFAULT_CHUNK_OVERLAP_CHARS,
  DEFAULT_MAX_CHUNK_CHARS,
  buildHybridIndex,
  buildKeywordIndex,
  buildLinkGraph,
  buildVectorIndex,
  chunkReference,
  contentSha,
  cosineSimilarity,
  createCachingEmbedder,
  createEmbeddingCache,
  createHashEmbedder,
  createLlamaEmbedder,
  embedChunksWithCache,
  extractRelevantSection,
  recallFromIndex,
  resolveEmbedder,
  truncateToTokenLimit,
} from "./store/index/index.js";
export {
  type MarkdownHandoffStoreDeps,
  type MarkdownMemoryStoreDeps,
  createMarkdownHandoffStore,
  createMarkdownMemoryStore,
  parseHandoffDocument,
  parseMemoryDocument,
  serializeHandoffDocument,
  serializeMemoryDocument,
} from "./store/markdown/index.js";
export {
  type JsonIntakeStoreDeps,
  type JsonSettingsStoreDeps,
  INTAKE_RUNS_FILE,
  LEGACY_INTAKE_RUNS_FILE,
  createJsonIntakeStore,
  createJsonCurationStore,
  createJsonSettingsStore,
  resolveIntakeRunsPath,
} from "./store/sidecar/index.js";
export {
  type LegacyArtifactReport,
  type MigrateDataDirOptions,
  type MigrateDataDirReport,
  type RemovedSettingReport,
  FRONTMATTER_SWEEP_COMMIT_MESSAGE,
  RETIRED_CURATOR_NOTE_FIELDS,
  RETIRED_FRONTMATTER_FIELDS,
  checkDataDirMigration,
  formatByteSize,
  migrateDataDir,
} from "./migrate-data-dir.js";
export {
  type CorpusIndex,
  type CorpusIndexOptions,
  type RecallMemoriesDeps,
  type RecallMemoriesOptions,
  type ReferenceHit,
  type SearchReferencesOptions,
  buildCorpusIndex,
  recallMemories,
  searchReferences,
} from "./store/corpus-index.js";
export { type MemoryWriteVerdict, routeMemoryWrite } from "./store/memory-routing.js";
export type { Memory, MemoryStore } from "./store/memory-store.js";
export {
  type AddendumRecord,
  type IntakeInboxOptions,
  type LibrarianStore,
  type LibrarianStoreOptions,
  type RollbackAddendumResult,
  type VaultActivityEntry,
  addendumPath,
  createLibrarianStore,
  resolveDataDir,
} from "./store/librarian-store.js";
export {
  type VaultCommitSource,
  type VaultRestoreDeps,
  type VaultRestoreOptions,
  type VaultRestoreResult,
  CurationRunInFlightError,
  VaultRestoreError,
  VaultRestoreInProgressError,
  VaultRestoreUnknownCommitError,
  classifyVaultCommit,
  preRestoreTagName,
  restoreVaultToCommit,
} from "./store/vault-restore.js";
export {
  CURATOR_PAUSE_KEY,
  CURATOR_PAUSE_TTL_MS,
  isCuratorPausedForRestore,
  pauseCuratorForRestore,
  resumeCuratorAfterRestore,
} from "./curator-pause.js";
export {
  type ApplyRestoreResult,
  type StageRestoreResult,
  PRE_RESTORE_BAK,
  RESTORE_FAILED_MARKER,
  RESTORE_MARKER,
  applyPendingRestore,
  stageRestore,
} from "./backup/restore-staging.js";
// Portable data export (distinct from backup — a human/tool-readable dump).
export { type ExportFormat, exportData } from "./backup/export.js";
export {
  type GithubSyncConfig,
  githubRepoSlugError,
  isValidGithubRepoSlug,
  resolveGithubSyncConfig,
} from "./backup/sync/github-config.js";
export { type RunBackupResult, runBackup, runBackupTick } from "./backup/run.js";
export {
  type BackupConfig,
  type BackupConfigPatch,
  type BackupRemote,
  BACKUP_BRANCH,
  BackupConfigPatchSchema,
  readBackupConfig,
  resolveBackupRemote,
  writeBackupConfig,
} from "./backup/config.js";
export {
  type BackupRun,
  type BackupRunStatus,
  type BackupRunTrigger,
  BACKUP_RUNS_FILE,
  latestTerminalBackupRun,
  listBackupRuns,
  lastSuccessfulBackupRun,
} from "./backup/runs.js";
export {
  type AgentTokenMeta,
  type CreatedAgentToken,
  createAgentToken,
  listAgentTokens,
  revokeAgentToken,
  verifyAgentToken,
} from "./auth/agent-tokens.js";
export {
  type LoadedAdminToken,
  loadOrCreateAdminTokenFile,
  parseAdminToken,
} from "./auth/admin-token.js";
export {
  type BootCredentialSignal,
  type BootCredentialsInput,
  type CredentialSource,
  type ResolvedBootCredentials,
  resolveBootCredentials,
} from "./auth/boot-credentials.js";
export {
  type AuthConfig,
  type AuthMethod,
  type AuthStatus,
  type EnableAuthInput,
  type EnableAuthResult,
  type OAuthClient,
  type OAuthProvider,
  deriveAuthSecret,
  enableAuth,
  getAuthConfig,
  getAuthStatus,
  isAuthConfigComplete,
  setEnabled,
  setOAuth,
  setOwner,
} from "./auth/auth-config.js";
export {
  type LockoutState,
  type OwnerAuthResult,
  type SettingsLike,
  LOCKOUT_KEY,
  PASSWORD_KEY,
  assertPasswordPolicy,
  authenticateOwner,
  consumeSetupLink,
  getLockoutState,
  hasOwnerPassword,
  mintSetupLink,
  ownerPasswordUsername,
  resetLockout,
  setOwnerPassword,
  verifyOwnerPassword,
} from "./auth/password.js";
export {
  type CompleteCurationRunInput,
  type CreateCurationRunInput,
  type CurationOperation,
  type CurationRun,
  type CurationStore,
  type FailCurationRunInput,
  type ListCurationRunsInput,
  type RecordCurationOperationInput,
} from "./store/curation-store.js";
export {
  type CompleteIntakeRunInput,
  type IntakeOperation,
  type IntakeRun,
  type IntakeStore,
  type CreateIntakeRunInput,
  type FailIntakeRunInput,
  type ListIntakeRunsInput,
  type RecordIntakeOperationInput,
} from "./store/intake-store.js";
export {
  type SplitMemoryRequest,
  type SplitMemoryStore,
  type SplitReplacement,
  splitMemory,
} from "./store/split-memory.js";
export {
  type MergeMemoryRequest,
  type MergeMemoryStore,
  mergeMemory,
} from "./store/merge-memory.js";
export type { SettingMeta, SettingsStore } from "./store/settings-store.js";
export {
  DEFAULT_PRIMER,
  LEGACY_AWARENESS_PRIMER_KEY,
  LEGACY_WORKING_STYLE_KEY,
  PRIMER_MAX_BYTES,
  PRIMER_PATH,
  type PrimerStore,
  readPrimer,
  seedPrimer,
  setPrimer,
} from "./primer.js";
export {
  type ClaimHandoffInput,
  type ClaimHandoffOutput,
  type HandoffSummary,
  type ListHandoffsInput,
  type ListHandoffsOutput,
  type StoreHandoffInput,
  type StoreHandoffOutput,
  ClaimHandoffInputSchema,
  ClaimHandoffOutputSchema,
  HandoffSummarySchema,
  HANDOFF_REQUIRED_HEADINGS,
  ListHandoffsInputSchema,
  ListHandoffsOutputSchema,
  StoreHandoffInputSchema,
  StoreHandoffOutputSchema,
} from "./schemas/handoff.js";
export {
  type ClaimedBy,
  type HandoffDetail,
  type HandoffStore,
  type ListHandoffsContext,
  type StoreHandoffContext,
  HandoffAlreadyClaimedError,
  HandoffNotFoundError,
} from "./store/handoff-store.js";
