#!/usr/bin/env node
// Reference generator for the docs-as-code site (docs-site spec, Phase 2 / K8).
//
// Produces the GENERATED technical-appendix pages under
// `apps/docs/src/content/docs/reference/` from their single canonical sources —
// so the reference can never silently drift from the code it describes. The
// companion `scripts/check-docs.mjs` regenerates and diffs in CI to enforce it.
//
// Source-of-truth & ordering (K8): this reads the BUILT packages
// (`@librarian/mcp-server`, the CLI dist) rather than re-parsing TypeScript, so
// `pnpm build` must run before `pnpm docs:gen` / `pnpm check:docs`. CI wires the
// check AFTER the build step so it can never pass against stale output.
//
// Run `pnpm docs:gen` to (re)write the pages; commit the result.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_PRIMER } from "@librarian/core";
import { tools } from "@librarian/mcp-server";
// The CLI help text is the canonical command surface. Read it from the built
// CLIs (K8 — built packages, not re-parsed source). `librarian` is the
// installer / self-host CLI (packages/installer-cli); `the-librarian` is the
// server-side admin CLI (packages/cli). Both runtimes export a `usage()`, hence
// the aliases.
import { authUsage } from "../packages/cli/dist/commands/auth.js";
import { usage as adminUsage, handoffsUsage } from "../packages/cli/dist/runtime.js";
import { usage as hostUsage } from "../packages/installer-cli/dist/runtime.js";
import { serverUsage } from "../packages/installer-cli/dist/server/index.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const referenceDir = path.join(repoRoot, "apps/docs/src/content/docs/reference");

// Fields the server fills in from the caller's authenticated token. They appear
// in a tool's input schema but are never passed by an agent — the reference
// must say so rather than present them as ordinary parameters (Jim's call).
const SERVER_POPULATED = new Set(["agent_id"]);

/** A `<!-- … -->` banner stamped onto every generated page. */
function generatedBanner(source) {
  return (
    `<!-- GENERATED by scripts/docs-gen.mjs from ${source}. ` +
    `Do not edit by hand — run \`pnpm docs:gen\` to update. -->`
  );
}

/** Render a JSON-Schema property's type as a short, human label. */
function renderType(prop) {
  const raw = prop?.type;
  // `["string", "null"]` unions model an optional/omittable field — show the
  // meaningful (non-null) member.
  const base = Array.isArray(raw) ? (raw.find((t) => t !== "null") ?? raw[0]) : raw;
  if (base === "array") {
    const itemType = prop?.items?.type;
    return itemType ? `${itemType}[]` : "array";
  }
  return base ?? "unknown";
}

/** required | optional | server-populated, for the parameter table. */
function renderRequiredness(name, schema) {
  if (SERVER_POPULATED.has(name)) return "server-populated";
  const required = Array.isArray(schema.required) ? schema.required : [];
  return required.includes(name) ? "required" : "optional";
}

/** The Markdown section for a single MCP verb. */
function renderVerbSection(tool) {
  const schema = tool.inputSchema ?? {};
  const properties = schema.properties ?? {};
  const lines = [`## \`${tool.name}\``, "", tool.description, ""];

  const names = Object.keys(properties);
  if (names.length === 0) {
    lines.push("_Takes no parameters._", "");
    return lines.join("\n");
  }

  lines.push("| Parameter | Type | Required | Description |");
  lines.push("| --- | --- | --- | --- |");
  for (const name of names) {
    const prop = properties[name];
    lines.push(
      `| \`${name}\` | \`${renderType(prop)}\` | ${renderRequiredness(name, schema)} | ${prop.description} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** The full `reference/mcp-verbs.md` page. */
export function renderMcpVerbs(toolList) {
  const header = [
    "---",
    "title: MCP verbs",
    "description: The seven memory and handoff verbs the server exposes to connected agents.",
    "---",
    "",
    generatedBanner("packages/mcp-server/src/mcp/tools/"),
    "",
    "These are the seven verbs the MCP server advertises to every connected agent.",
    "Each verb's description below is the exact text an agent receives at call time.",
    "Parameters marked **server-populated** are resolved from your authenticated token —",
    "you never pass them.",
    "",
  ].join("\n");

  const sections = toolList.map(renderVerbSection).join("\n");
  return `${header}\n${sections}`;
}

/** The canonical help text of every CLI surface, gathered from the built CLIs.
 *  Exported so the parity test can diff the page against it verbatim. */
export function collectCliHelp() {
  return {
    hostUsage: hostUsage(),
    serverUsage: serverUsage(),
    adminUsage: adminUsage(),
    handoffsUsage: handoffsUsage(),
    authUsage: authUsage(),
  };
}

/** A fenced, plain-text code block. Fences render the help verbatim — angle
 *  brackets and backticks in usage text are inert inside a code block. */
function codeFence(text) {
  return ["```text", text.trimEnd(), "```"].join("\n");
}

/** The full `reference/cli.md` page — both CLIs, every command, with flags. */
export function renderCli(help) {
  const header = [
    "---",
    "title: CLI",
    "description: The two command-line tools — librarian (install and self-host) and the-librarian (server-side admin).",
    "---",
    "",
    generatedBanner("the built CLIs (packages/installer-cli, packages/cli)"),
    "",
    "The Librarian ships two command-line tools. `librarian` runs on a client or",
    "host machine to install the integration into your harnesses and, optionally,",
    "to self-host the server. `the-librarian` runs against the memory vault itself",
    "for backups, exports, handoff inspection, and auth recovery.",
    "",
  ].join("\n");

  const body = [
    "## `librarian` — install and self-host",
    "",
    codeFence(help.hostUsage),
    "",
    "### `librarian server`",
    "",
    codeFence(help.serverUsage),
    "",
    "## `the-librarian` — server-side admin",
    "",
    codeFence(help.adminUsage),
    "",
    "### `the-librarian handoffs`",
    "",
    codeFence(help.handoffsUsage),
    "",
    "### `the-librarian auth`",
    "",
    codeFence(help.authUsage),
    "",
  ].join("\n");

  return `${header}\n${body}`;
}

/** The full `reference/primer.md` page — the shipped default primer, verbatim. */
export function renderPrimer(primer) {
  const header = [
    "---",
    "title: Primer",
    "description: The connect-time instructions every harness receives — the shipped default primer.",
    "---",
    "",
    generatedBanner("packages/core/src/primer.ts (DEFAULT_PRIMER)"),
    "",
    "This is the primer The Librarian ships by default: the connect-time",
    "instructions delivered to every harness over MCP. A deployment's *live* primer",
    "is operator-editable at `vault/primer.md`; this page documents the shipped",
    "default, reproduced verbatim.",
    "",
  ].join("\n");
  return `${header}\n${codeFence(primer)}\n`;
}

/** Embed a canonical Markdown doc as a reference page. The transform is
 *  deterministic so `check-docs.mjs` can regenerate-and-diff: strip the source's
 *  leading H1 (the Starlight frontmatter title is the page's H1) and reduce
 *  repo-relative links — which point at repo files, not site routes, and would
 *  fail the internal-link checker — to their link text. External links and
 *  in-page anchors are left intact. */
export function includeMarkdown(raw, { title, description, source }) {
  let body = raw.replace(/^#\s+[^\n]*\n+/, "");
  body = body.replace(/\[([^\]]+)\]\((?!https?:\/\/|#|\/)[^)]*\)/g, "$1");
  const header = [
    "---",
    `title: ${title}`,
    `description: ${description}`,
    "---",
    "",
    generatedBanner(source),
    "",
    `_Reproduced from \`${source}\` (the canonical source) — edit that file, not this page._`,
    "",
  ].join("\n");
  return `${header}\n${body.trimEnd()}\n`;
}

function readDoc(relPath) {
  return fs.readFileSync(path.join(repoRoot, relPath), "utf8");
}

/** Map of repo-relative output path → file contents. The single place that
 *  enumerates what the reference comprises; `check-docs.mjs` consumes it too. */
export function generateReference() {
  return {
    "apps/docs/src/content/docs/reference/mcp-verbs.md": renderMcpVerbs(tools),
    "apps/docs/src/content/docs/reference/cli.md": renderCli(collectCliHelp()),
    "apps/docs/src/content/docs/reference/primer.md": renderPrimer(DEFAULT_PRIMER),
    "apps/docs/src/content/docs/reference/slash-commands.md": includeMarkdown(
      readDoc("docs/slash-commands.md"),
      {
        title: "Slash commands",
        description:
          "The four cross-harness slash commands — handoff, takeover, learn, toggle-private.",
        source: "docs/slash-commands.md",
      },
    ),
    "apps/docs/src/content/docs/reference/capture-matrix.md": includeMarkdown(
      readDoc("docs/harness-capture-capability.md"),
      {
        title: "Harness capture matrix",
        description: "Which harnesses support automatic transcript capture, and how.",
        source: "docs/harness-capture-capability.md",
      },
    ),
  };
}

function writeAll() {
  fs.mkdirSync(referenceDir, { recursive: true });
  const files = generateReference();
  for (const [relPath, contents] of Object.entries(files)) {
    const abs = path.join(repoRoot, relPath);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    // Trailing newline so the file is POSIX-clean and prettier-stable.
    fs.writeFileSync(abs, contents.endsWith("\n") ? contents : `${contents}\n`);
    console.log(`docs:gen wrote ${relPath}`);
  }
}

// Only write files when run directly (`pnpm docs:gen`); importing the render
// functions (the parity test, check-docs.mjs) must have no side effects.
if (import.meta.url === `file://${process.argv[1]}`) {
  writeAll();
}
